#%RAML 1.0
---
title: Picap API
baseUri: http://picap.lvh.me:3000/api
version: v1
/pssg:
  description: pssg endpoint description example 1
  /passengers:
    description: Passengers endpoint description example 2
    /resellers:
      description: resellers endpoint description example 2
      get:
        description: get all resellers json format